# Generated by Django 3.2.5 on 2021-07-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='priceperpound',
        ),
    ]
