# Generated by Django 3.2.5 on 2021-07-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredient_priceperpound'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='priceperpound',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
