# Generated by Django 3.2.5 on 2021-07-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredient_priceperpound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='priceperpound',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price_per_pound',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
