# Generated by Django 3.2.5 on 2021-07-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_auto_20210712_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient',
            new_name='name',
        ),
    ]
