# Generated by Django 3.2.5 on 2021-07-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0003_auto_20210713_2051'),
        ('ingredients', '0005_rename_ingredient_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='menuitem',
            field=models.ManyToManyField(to='menuitems.MenuItem'),
        ),
    ]
