# Generated by Django 3.2.5 on 2021-07-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0003_auto_20210713_2051'),
        ('ingredients', '0007_remove_ingredient_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='menuitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menuitems.menuitem'),
        ),
    ]
