# Generated by Django 3.2.5 on 2021-07-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
