# Generated by Django 3.2.5 on 2021-07-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0002_rename_ingredient_menuitem_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredient_weight',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='ingredients',
        ),
    ]
