# Generated by Django 3.2.5 on 2021-07-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_remove_ingredient_menuitem'),
        ('menuitems', '0003_auto_20210713_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ingredient',
            field=models.ManyToManyField(to='ingredients.Ingredient'),
        ),
    ]
