# Generated by Django 3.2.5 on 2021-07-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0004_menuitem_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
