# Generated by Django 3.2.5 on 2021-07-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0006_remove_menuitem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='ingredients',
            field=models.JSONField(null=True),
        ),
    ]
