# Generated by Django 3.2.5 on 2021-07-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuitems', '0007_menuitem_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menuImg',
            field=models.ImageField(null=True, upload_to='menuitems/'),
        ),
    ]
